### ISSUE TITLE
Green and yellow colors are swapped

### ISSUE THREAD

**Issue by actionless** [dracula/base16-dracula-scheme#9]
In base16 themes colors are ordered like that:
![image](https://user-images.githubusercontent.com/1655669/51069039-7bea5080-1627-11e9-8633-e31e9d7d5e5c.png)

While in Dracula theme Green and Yellow colors look swapped:

![2019-01-12--1547265709_238x293_scrot](https://user-images.githubusercontent.com/1655669/51069028-2d3cb680-1627-11e9-8288-b131a42bd26c.png)

i think it should instead looks like that:
```diff
@@ -9,9 +9,9 @@ base05: "e9e9f4" #foreground
 base06: "f1f2f8"
 base07: "f7f7fb"
 base08: "ea51b2"
-base09: "b45bcf"
-base0A: "00f769"
-base0B: "ebff87"
+base09: "ebff87"
+base0A: "ebff87"
+base0B: "00f769"
 base0C: "a1efe4"
 base0D: "62d6e8"
 base0E: "b45bcf"
```

![2019-01-12--1547265777_234x291_scrot](https://user-images.githubusercontent.com/1655669/51069036-58bfa100-1627-11e9-9fdc-8af5681d8a15.png)

**Comment by mikebarkmin** [comment]
Thanks for your advice. We are currently discussing how we would like to change the base16 scheme to fit the overall dracula theme better. You can find our discussion in #8

**Comment by actionless** [comment]
ok
